# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflows deploys the SAP SYSTEM with GitHub Actions              |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name:                                             04 - SAP SID Infrastructure deployment
run-name:                                         SAP SID Infrastructure by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      sap_system_identifier:
        description:                              "SAP System identifier (SID)"
        required:                                 true
        default:                                  "X00"
        type:                                     string
      workload_zone:
        description:                              "Workload Environment ..."
        required:                                 true
        type:                                     environment
      test:
        description:                              "Test deployment without applying changes"
        type:                                     boolean
        default:                                  false

permissions:
  contents:                                       write
  id-token:                                       write
  issues:                                         write

env:
  TF_IN_AUTOMATION:                               ${{ vars.TF_IN_AUTOMATION }}
  TF_LOG:                                         ${{ vars.TF_LOG }}
  ANSIBLE_CORE_VERSION:                           ${{ vars.ANSIBLE_CORE_VERSION }}
  TF_VERSION:                                     ${{ vars.TF_VERSION }}

jobs:
  deploy_sap_infrastructure:
    name:                                         Deploy SAP Infrastructure
    environment:                                  ${{ inputs.workload_zone }}
    runs-on:                                      self-hosted
    container:
      image:                                      ${{ vars.DOCKER_IMAGE }}

    steps:
      - name:                                     Get app token
        id:                                       get_workflow_token
        uses:                                     actions/create-github-app-token@v2
        with:
          app-id:                                 ${{ secrets.APPLICATION_ID }}
          private-key:                            ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name:                                     Configure Git Safe Directory
        run:                                      |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"

      - name:                                     Checkout repository
        uses:                                     actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth:                            0

      - name:                                     Azure Login with User Managed Identity
        if:                                       ${{ vars.USE_MSI == 'true' }}
        uses:                                     Azure/login@v2
        with:
          auth-type:                              IDENTITY
          client-id:                              ${{ vars.ARM_CLIENT_ID }}
          tenant-id:                              ${{ vars.ARM_TENANT_ID }}
          subscription-id:                        ${{ vars.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession:                     false

      - name:                                     Azure Login with Service Principal
        if:                                       ${{ vars.USE_MSI != 'true' }}
        uses:                                     Azure/Login@v2
        with:
          creds:                                  |
           {
                                                  "clientId": "${{ vars.ARM_CLIENT_ID }}",
                                                  "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
                                                  "subscriptionId": "${{ vars.ARM_SUBSCRIPTION_ID }}",
                                                  "tenantId": "${{ vars.ARM_TENANT_ID }}"
           }

      - name:                                     Deploy SAP Infrastructure
        run:                                      |
          cd ${SAP_AUTOMATION_REPO_PATH}
          chmod +x deploy/scripts/pipeline_scripts/03-sap-system-deployment.sh
          deploy/scripts/pipeline_scripts/03-sap-system-deployment.sh
        env:
          APPLICATION_CONFIGURATION_NAME:         ${{ vars.APPLICATION_CONFIGURATION_NAME }}
          CONTROL_PLANE_NAME:                     ${{ vars.CONTROL_PLANE_NAME }}
          WORKLOAD_ZONE_NAME:                     ${{ inputs.workload_zone }}
          APP_TOKEN:                              ${{ steps.get_workflow_token.outputs.token }}
          ARM_CLIENT_ID:                          ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:                      ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID:                    ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:                          ${{ vars.ARM_TENANT_ID }}
          TEST_ONLY:                              ${{ inputs.test }}
          SAP_SYSTEM_TFVARS_FILENAME:             ${{ inputs.workload_zone }}-${{ inputs.sap_system_identifier }}.tfvars
          SAP_SYSTEM_FOLDERNAME:                  ${{ inputs.workload_zone }}-${{ inputs.sap_system_identifier }}
          USE_MSI:                                ${{ vars.USE_MSI }}
          tf_version:                             ${{ env.TF_VERSION }}
