---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflows performs the software installation                      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name:                                             6.3 - Application Tier Installation
run-name:                                         Application Tier Installation by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      sap_system_identifier:
        description:                              "SAP System Identifier (SID)"
        default:                                  "X00"
        required:                                 true
        type:                                     string
      workload_zone_name:
        description:                              "Workload Environment name (e.g. DEV-WEEU-SAP01)"
        type:                                     environment
        required:                                 true
      bom_name:
        description:                              "Bill of Materials name (BoM)"
        required:                                 true
        type:                                     choice
        options:
          - S42023SPS00_v88_0ms (HANA_2_00_088)
          - S42023SPS00_v0005ms (HANA_2_00_081)
          - S42023SPS00_v0003ms (HANA_2_00_077)
          - S42023SPS00_v0004ms (HANA_2_00_077 - dynamic)
          - S42022SPS00_v0004ms (HANA_2_00_077 - dynamic)
          - S42022SPS00_v0005ms (HANA_2_00_076)
          - S42022SPS00_v0006ms (HANA_2_00_077)
          - S42021ISS00_v0003ms (HANA_2_00_067)
          - S42020ISS00_v0004ms (HANA_2_00_067 - dynamic)
          - S42020SPS03_v0005ms (HANA_2_00_067)
          - S41909SPS03_v0012ms (HANA_2_00_059 - dynamic)
          - S41909ISS00_v0013ms (HANA_2_00_059)
          - NW750SPS20_v0005ms (HANA_2_00_067)
          - NW750SPS20_v0006ms (HANA_2_00_067 - dynamic)
          - NW750SPS25_JAVA_v0001ms (HANA_2_00_067)
          - NW752SPS09_v0002ms (HANA_2_00_067)
          - NW750SPS25_JAVA__HANA_v0001ms (HANA_2_00_067)
          - NW750SPS20_DB2_v0002ms (DB2_UDB_11_5)
          - NW750_ORACLE_19_v0001ms (Oracle_19)
          - NW750_ORACLE_19_v0002ms (Oracle_19 - Kernel 754)
          - NW750_ORACLE_19_ASM_v0002ms (Oracle_19)
          - NW750SPS25_JAVA_Oracle_19_00_v0001ms (Oracle_19)
          - NW750SPS20_SYBASE_v0003ms (ASE_16_0_3)
          - NW750_MSSQL_v0003ms (MSSQL_2019)
          - SOLMAN_72SR2_JAVA_v0001ms (HANA_2_00_081)
          - SOLMAN_72SR2_v0001ms (HANA_2_00_081)
          - HANA_2_00_059_v0011ms
          - HANA_2_00_067_v0006ms
          - HANA_2_00_076_v0001ms
          - HANA_2_00_077_v0002ms
          - HANA_2_00_081_v0001ms
          - DB2_UDB_11_5_v0001ms
          - ORACLE_19_00_v0003ms
          - ORACLE_19_00_ASM_v0001ms
          - ORACLE_19_00_ORA_MSID_v0002ms
          - MSSQLSRV_2019_v0001ms
          - SYBASE_1603SP15_v0003ms
          - XBOM_Tester
      extra_params:
        description:                              "Extra Parameters"
        type:                                     string
        default:                                  " "
      pas_installation:
        description:                              "Primary Application Server Installation"
        type:                                     boolean
        default:                                  true
      application_server_installation:
        description:                              "Additional Application Server Installation"
        type:                                     boolean
        default:                                  true
      webdispatcher_installation:
        description:                              "Web Dispatcher Installation"
        type:                                     boolean
        default:                                  false
permissions:
  contents:                                       write
  id-token:                                       write
  issues:                                         write

env:
  TF_IN_AUTOMATION:                               ${{ vars.TF_IN_AUTOMATION }}
  TF_LOG:                                         ${{ vars.TF_LOG }}
  ANSIBLE_CORE_VERSION:                           ${{ vars.ANSIBLE_CORE_VERSION }}
  TF_VERSION:                                     ${{ vars.TF_VERSION }}

jobs:
  application_tier_installation:
    name:                                         Application Tier Installation
    environment:                                  ${{ inputs.workload_zone_name }}
    runs-on:                                      self-hosted
    container:
      image:                                      ${{ vars.DOCKER_IMAGE }}
    steps:
      - name:                                     Get app token
        id:                                       get_workflow_token
        uses:                                     actions/create-github-app-token@v2
        with:
          app-id:                                 ${{ secrets.APPLICATION_ID }}
          private-key:                            ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name:                                     Checkout repository
        uses:                                     actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth:                            0

      - name:                                     Azure Login with User Managed Identity
        if:                                       ${{ vars.USE_MSI == 'true' }}
        uses:                                     Azure/login@v2
        with:
          auth-type:                              IDENTITY
          client-id:                              ${{ vars.ARM_CLIENT_ID }}
          tenant-id:                              ${{ vars.ARM_TENANT_ID }}
          subscription-id:                        ${{ vars.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession:                     false

      - name:                                     Azure Login with Service Principal
        if:                                       ${{ vars.USE_MSI != 'true' }}
        uses:                                     Azure/Login@v2
        with:
          creds:                                  |
            {
                                                  "clientId": "${{ vars.ARM_CLIENT_ID }}",
                                                  "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
                                                  "subscriptionId": "${{ vars.ARM_SUBSCRIPTION_ID }}",
                                                  "tenantId": "${{ vars.ARM_TENANT_ID }}"
            }

      - name:                                     BOM Name
        if:                                       ${{ github.event.inputs.bom_name != '' }}
        id:                                       bom
        run:                                      |
          input="${{ github.event.inputs.bom_name }}"
          bom_base_name=$(echo "$input" | cut -d' ' -f1)
          echo "bom_base_name=$bom_base_name" >> "$GITHUB_OUTPUT"

      - name:                                     Preparation for Ansible
        id:                                       preparation
        run:                                      |
          cd ${SAP_AUTOMATION_REPO_PATH}
          chmod +x deploy/scripts/pipeline_scripts/05-DB-and-SAP-installation-prepare.sh
          deploy/scripts/pipeline_scripts/05-DB-and-SAP-installation-prepare.sh
          echo "SAP_AUTOMATION_REPO_PATH=${SAP_AUTOMATION_REPO_PATH}" >> $GITHUB_ENV
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        env:
          APP_TOKEN:                              ${{ steps.get_workflow_token.outputs.token }}
          APPLICATION_CONFIGURATION_NAME:         ${{ vars.APPLICATION_CONFIGURATION_NAME }}
          ARM_CLIENT_ID:                          ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:                      ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID:                    ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:                          ${{ vars.ARM_TENANT_ID }}
          ARM_OBJECT_ID:                          ${{ vars.ARM_OBJECT_ID }}
          BOM_BASE_NAME:                          ${{ steps.bom.outputs.bom_base_name }}
          SAP_SYSTEM_CONFIGURATION_NAME:          ${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}
          CONTROL_PLANE_NAME:                     ${{ vars.CONTROL_PLANE_NAME }}
          WORKLOAD_ZONE_NAME:                     ${{ inputs.workload_zone_name }}
          SCRIPT_PATH:                            ./sap-automation/deploy/pipelines/templates/*.sh
          PIPELINE_EXTRA_PARAMETERS:              ${{ inputs.EXTRA_PARAMS }}
          USE_MSI:                                ${{ vars.USE_MSI }}

      - name:                                     Parameter Validation
        uses:                                     ./.github/actions/run-ansible
        with:
          displayName:                            "Parameter validation"
          ansibleFilePath:                        "${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/playbook_00_validate_parameters.yaml"
          APPLICATION_CONFIGURATION_NAME:         ${{ vars.APPLICATION_CONFIGURATION_NAME }}
          ARM_CLIENT_ID:                          ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:                      ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID:                    ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:                          ${{ vars.ARM_TENANT_ID }}
          CONTROL_PLANE_NAME:                     ${{ vars.CONTROL_PLANE_NAME }}
          CONTROL_PLANE_SUBSCRIPTION_ID:          ${{ steps.preparation.outputs.CP_SUBSCRIPTION }}
          SAP_AUTOMATION_REPO_PATH:               ${{ env.SAP_AUTOMATION_REPO_PATH }}
          TERRAFORM_STATE_STORAGE_ACCOUNT:        ${{ vars.TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME }}
          USE_MSI:                                ${{ vars.USE_MSI }}
          WORKLOAD_ZONE_NAME:                     ${{ inputs.workload_zone_name }}
          ansibleConfigPath:                      ${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/ansible.cfg
          extraParams:                            ${{ steps.preparation.outputs.NEW_PARAMETERS }}
          sapParams:                              ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/sap-parameters.yaml
          sidHosts:                               ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/${{ inputs.sap_system_identifier }}_hosts.yaml
          vaultName:                              ${{ steps.preparation.outputs.VAULT_NAME }}

      - name:                                     Primary Application Server Installation
        if:                                       ${{ github.event.inputs.pas_installation == 'true' }}
        uses:                                     ./.github/actions/run-ansible
        with:
          displayName:                            "Primary Application Server Installation"
          ansibleFilePath:                        ${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/playbook_05_02_sap_pas_install.yaml
          APPLICATION_CONFIGURATION_NAME:         ${{ vars.APPLICATION_CONFIGURATION_NAME }}
          ARM_CLIENT_ID:                          ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:                      ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID:                    ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:                          ${{ vars.ARM_TENANT_ID }}
          CONTROL_PLANE_NAME:                     ${{ vars.CONTROL_PLANE_NAME }}
          CONTROL_PLANE_SUBSCRIPTION_ID:          ${{ steps.preparation.outputs.CP_SUBSCRIPTION }}
          SAP_AUTOMATION_REPO_PATH:               ${{ env.SAP_AUTOMATION_REPO_PATH }}
          TERRAFORM_STATE_STORAGE_ACCOUNT:        ${{ vars.TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME }}
          USE_MSI:                                ${{ vars.USE_MSI }}
          WORKLOAD_ZONE_NAME:                     ${{ inputs.workload_zone_name }}
          ansibleConfigPath:                      ${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/ansible.cfg
          extraParams:                            ${{ steps.preparation.outputs.NEW_PARAMETERS }}
          sapParams:                              ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/sap-parameters.yaml
          sidHosts:                               ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/${{ inputs.sap_system_identifier }}_hosts.yaml
          vaultName:                              ${{ steps.preparation.outputs.VAULT_NAME }}
      - name:                                     Additional Application Server Installation
        if:                                       ${{ github.event.inputs.application_server_installation == 'true' }}
        uses:                                     ./.github/actions/run-ansible
        with:
          displayName:                            "Application Server Installation"
          ansibleFilePath:                        ${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/playbook_05_03_sap_app_install.yaml
          APPLICATION_CONFIGURATION_NAME:         ${{ vars.APPLICATION_CONFIGURATION_NAME }}
          ARM_CLIENT_ID:                          ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:                      ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID:                    ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:                          ${{ vars.ARM_TENANT_ID }}
          CONTROL_PLANE_NAME:                     ${{ vars.CONTROL_PLANE_NAME }}
          CONTROL_PLANE_SUBSCRIPTION_ID:          ${{ steps.preparation.outputs.CP_SUBSCRIPTION }}
          SAP_AUTOMATION_REPO_PATH:               ${{ env.SAP_AUTOMATION_REPO_PATH }}
          TERRAFORM_STATE_STORAGE_ACCOUNT:        ${{ vars.TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME }}
          USE_MSI:                                ${{ vars.USE_MSI }}
          WORKLOAD_ZONE_NAME:                     ${{ inputs.workload_zone_name }}
          ansibleConfigPath:                      ${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/ansible.cfg
          extraParams:                            ${{ steps.preparation.outputs.NEW_PARAMETERS }}
          sapParams:                              ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/sap-parameters.yaml
          sidHosts:                               ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/${{ inputs.sap_system_identifier }}_hosts.yaml
          vaultName:                              ${{ steps.preparation.outputs.VAULT_NAME }}

      - name:                                     Web Dispatcher Installation
        if:                                       ${{ github.event.inputs.webdispatcher_installation == 'true' }}
        uses:                                     ./.github/actions/run-ansible
        with:
          displayName:                            "Web Dispatcher Installation"
          ansibleFilePath:                        ${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/playbook_05_04_sap_web_install.yaml
          APPLICATION_CONFIGURATION_NAME:         ${{ vars.APPLICATION_CONFIGURATION_NAME }}
          ARM_CLIENT_ID:                          ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:                      ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID:                    ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:                          ${{ vars.ARM_TENANT_ID }}
          CONTROL_PLANE_NAME:                     ${{ vars.CONTROL_PLANE_NAME }}
          CONTROL_PLANE_SUBSCRIPTION_ID:          ${{ steps.preparation.outputs.CP_SUBSCRIPTION }}
          SAP_AUTOMATION_REPO_PATH:               ${{ env.SAP_AUTOMATION_REPO_PATH }}
          TERRAFORM_STATE_STORAGE_ACCOUNT:        ${{ vars.TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME }}
          USE_MSI:                                ${{ vars.USE_MSI }}
          WORKLOAD_ZONE_NAME:                     ${{ inputs.workload_zone_name }}
          ansibleConfigPath:                      ${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/ansible.cfg
          extraParams:                            ${{ steps.preparation.outputs.NEW_PARAMETERS }}
          sapParams:                              ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/sap-parameters.yaml
          sidHosts:                               ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/${{ inputs.sap_system_identifier }}_hosts.yaml
          vaultName:                              ${{ steps.preparation.outputs.VAULT_NAME }}

      - name:                                     Post Configuration Actions
        uses:                                     ./.github/actions/run-ansible
        with:
          displayName:                            "Post Configuration Actions"
          ansibleFilePath:                        ${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/playbook_08_00_00_post_configuration_actions.yaml
          APPLICATION_CONFIGURATION_NAME:         ${{ vars.APPLICATION_CONFIGURATION_NAME }}
          ARM_CLIENT_ID:                          ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:                      ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID:                    ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:                          ${{ vars.ARM_TENANT_ID }}
          CONTROL_PLANE_NAME:                     ${{ vars.CONTROL_PLANE_NAME }}
          CONTROL_PLANE_SUBSCRIPTION_ID:          ${{ steps.preparation.outputs.CP_SUBSCRIPTION }}
          SAP_AUTOMATION_REPO_PATH:               ${{ env.SAP_AUTOMATION_REPO_PATH }}
          TERRAFORM_STATE_STORAGE_ACCOUNT:        ${{ vars.TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME }}
          USE_MSI:                                ${{ vars.USE_MSI }}
          WORKLOAD_ZONE_NAME:                     ${{ inputs.workload_zone_name }}
          ansibleConfigPath:                      ${{ env.SAP_AUTOMATION_REPO_PATH }}/deploy/ansible/ansible.cfg
          extraParams:                            ${{ steps.preparation.outputs.NEW_PARAMETERS }}
          sapParams:                              ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/sap-parameters.yaml
          sidHosts:                               ${{ env.GITHUB_WORKSPACE }}/WORKSPACES/SYSTEM/${{ inputs.workload_zone_name }}-${{ inputs.sap_system_identifier }}/${{ inputs.sap_system_identifier }}_hosts.yaml
          vaultName:                              ${{ steps.preparation.outputs.VAULT_NAME }}
